baseURL = "https://JunkMuffler.com/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Junk Muffler"
enableEmoji = true

# Change the default theme to be use when building the site with Hugo
theme = "uBlogger"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  
[params]
  # uBlogger theme version
  version = "1.2.X"
  defaultTheme = "light"
  dateFormat = "2006-01-02"
  title = "Junk Muffler"
  [params.social]
    [params.social.Youtubechannel]
        # weight when arranging icons (the greater the weight, the later the icon is positioned)
        weight = 1
        # your social ID
        id = "UCz6hXeWw6SNTHwWPV6pltgg"
        # prefix of your social link
        prefix = "https://www.youtube.com/channel/"
        # content hovering on the icon
        title = "YouTube"
    [params.social.Twitter]
      # weight when arranging icons (the greater the weight, the later the icon is positioned)
      weight = 3
      # your social ID
      id = "junkmuffler"
      # prefix of your social link
      prefix = "https://www.twitter.com/"
      # content hovering on the icon
      title = "Twitter"
  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    custom = 'Made With ❤ by Junk Muffler'
    # whether to show Hugo and theme info
    hugo = false
    # whether to show copyright info
    copyright = true
    # whether to show the author
    author = false
    # site creation time
    since = 2019
    icp = ""

[languages]
  [languages.en]
    weight = 1
    # language code
    languageCode = "en"
    # language name
    languageName = "English"
    # whether to include Chinese/Japanese/Korean
    hasCJKLanguage = false
    # default amount of posts in each pages
    paginate = 12
     # copyright description used only for seo schema
    copyright = "All Rights Reserved"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "music"
        # you can add extra information before the name (HTML format is supported), such as icons
        pre = ""
        # you can add extra information after the name (HTML format is supported), such as icons
        post = ""
        name = "Music"
        url = "/categories/music/"
        # title will be shown when you hover on this menu link
        title = ""
        weight = 1
      [[languages.en.menu.main]]
        identifier = "news"
        # you can add extra information before the name (HTML format is supported), such as icons
        pre = ""
        # you can add extra information after the name (HTML format is supported), such as icons
        post = ""
        name = "News"
        url = "/categories/news/"
        # title will be shown when you hover on this menu link
        title = ""
        weight = 2
      [[languages.en.menu.main]]
        identifier = "youtube"
        pre = "<i class='fab fa-youtube fa-fw'></i>"
        url = "https://www.youtube.com/channel/UCz6hXeWw6SNTHwWPV6pltgg"
        title = "YouTube"
        weight = 4
      [[languages.en.menu.main]]
        identifier = "twitter"
        pre = "<i class='fab fa-twitter fa-fw'></i>"
        url = "https://twitter.com/JunkMuffler"
        title = "Twitter"
        weight = 6
    [languages.en.params]
      # site description
      description = "Maker of questionable art, music, and random stuff."
      [languages.en.params.app]
        # whether to omit favicon resource links
        noFavicon = false
        # modern SVG favicon to use in place of older style .png and .ico files
        svgFavicon = "/favicon/favicon-32x32.png"
    [languages.en.params.search]
        enable = true
        # type of search engine ("lunr", "algolia")
        type = "lunr"
        # max index length of the chunked content
        contentLength = 4000
        # placeholder of the search bar
        placeholder = ""
        # max number of results length
        maxResultLength = 10
        # snippet length of the result
        snippetLength = 30
        # HTML tag name of the highlight part in results
        highlightTag = "em"
        # whether to use the absolute URL based on the baseURL in search index
        absoluteURL = false
    [languages.en.params.home]
        # amount of RSS pages
        rss = 10
        # Home page profile
        [languages.en.params.home.profile]
          enable = true
          # Gravatar Email for preferred avatar in home page
          gravatarEmail = ""
          # URL of avatar shown in home page
          avatarURL = "/images/avatar.jpg"
          # title shown in home page (HTML format is supported)
          title = "Junk Muffler"
          # subtitle shown in home page (HTML format is supported)
          subtitle = "Comedian, musician, and purveyor of questionable novelty songs."
          # whether to use typeit animation for subtitle
          typeit = false
          # whether to show social links
          social = true
          # disclaimer (HTML format is supported)
          disclaimer = ""
        # Home page posts
        [languages.en.params.home.posts]
          enable = true
          # special amount of posts in each home posts page
          paginate = 6
          

          

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration
    noClasses = false